### ISSUE TITLE
running cukePlugin fails of not applicable Yaml.load() method

### ISSUE THREAD

**Issue by jonnybbb** [RobertFischer/gradle-plugins#1]
When running gradle -d runFeatures the build failes with an excetion that 
No signature of method: static org.yaml.snakeyaml.Yaml.load() is applicable for argument types: (java.io.BufferedInputStream) 

http://gist.github.com/288325 

i run Mac OSX Snow Leopard, Java 1.6 gradle 0.8

**Comment by RobertFischer** [comment]
It's not pulling down Snake Yaml for some reason.  Not sure why that would be...

**Comment by jonnybbb** [comment]
cleaned up the gradle cache and the yaml is downloaded sucessfully, but the error still exists.
http://gist.github.com/288576

**Comment by jonnybbb** [comment]
I could get rid of the problem by creating a new Instance 
      def Yaml = project.classFor("org.yaml.snakeyaml.Yaml", "jrubyPluginYaml").newInstance()

The second issue i run into was that the cucumber directory was to
.gem/jruby/1.8/doc/cucumber-0.6.2/bin/cucumber
instead of
.gem/jruby/1.8/doc/cucumber-0.6.2/bin

but now i have the issue that an asm class could not be loaded.
java.lang.NoClassDefFoundError: org/objectweb/asm/Opcodes (NativeException)

http://gist.github.com/289309

**Comment by RobertFischer** [comment]
You're classloaders are all messed up.  What's your script look like?

Here's an example of a working script from one of my projects: http://gist.github.com/289437
