### ISSUE TITLE
CukePlugin: Can't access java methods in jruby step definitions

### ISSUE THREAD

**Issue by dokipen** [RobertFischer/gradle-plugins#13]
I ended up abandoning the CukePlugin because I couldn't access instance methods of the Api class from my jruby step definitions.  Methods like toString() worked fine (because they are inherited from Object, I assume), but methods like oembed couldn't be invoked.  (MethodMissing error).

**Comment by RobertFischer** [comment]
That's odd: I'm doing precisely that with Ashlar. Do you have the necessary classes on your test configuration?

**Comment by dokipen** [comment]
The problem ended up being that my class wasn't public, but package.  What threw me off was that it worked in straight cuke4duke, but not your plugin.  It would seem that your plugin was doing things right though.
