### ISSUE TITLE
Unable to use RunJRubyPlugin

### ISSUE THREAD

**Issue by jeppenejsum** [RobertFischer/gradle-plugins#14]
I've just returned to try out RunJRubyPlugin and am having some problems. This may be caused by the fact that this is a new machine, with no ruby, jruby etc installed.

I've tried various versions of gradle & the plugins. This is with gradle-1.0-milestone-1 and 0.7.1-SNAPSHOT.

First occurence of project.useGem("rake") results in this:

<code>
10:06:24.606 [INFO] [com.smokejumperit.gradle.RunJRubyPlugin] Running JRuby: -S gem install --no-rdoc --no-ri rake
Fetching: rake-0.8.7.gem (100%)t] Fetching: rake-0.8.7.gem
10:06:34.424 [ERROR] [system.err] ERROR:  While executing gem ... (Gem::FilePermissionError)
10:06:34.426 [ERROR] [system.err]     You don't have write permissions into the file:/Users/jeppe/.gradle/cache/org.jruby/jruby-complete/jars/jruby-complete-1.6.0.jar!/META-INF/jruby.home/lib/ruby/gems/1.8 directory.
</code>

Running again gives:
<code>
10:09:45.981 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.IllegalArgumentException: Neither path nor baseDir may be null or empty string. path='null' basedir='/Users/jeppe/Documents/workspaces/fleetzone/fleetweb'
10:09:45.981 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.BaseDirConverter.doResolve(BaseDirConverter.java:64)
10:09:45.982 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:48)
10:09:45.982 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:44)
10:09:45.984 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.BaseDirConverter.resolveAsRelativePath(BaseDirConverter.java:39)
10:09:45.986 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.DefaultFileOperations.relativePath(DefaultFileOperations.java:99)
10:09:45.987 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractProject.relativePath(AbstractProject.java:731)
10:09:45.987 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.FileOperations$relativePath.call(Unknown Source)
10:09:45.988 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.ProjectExtPlugin$_apply_closure1.doCall(ProjectExtPlugin.groovy:13)
10:09:45.988 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure6.doCall(RunJRubyPlugin.groovy:61)
10:09:45.988 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure9.doCall(RunJRubyPlugin.groovy:93)
10:09:45.988 [ERROR] [org.gradle.BuildExceptionReporter]    at build_58n6pgnaovl3erg7mhkqgfg4q2.runDBTask(/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle:252)
10:09:45.989 [ERROR] [org.gradle.BuildExceptionReporter]    at build_58n6pgnaovl3erg7mhkqgfg4q2$_run_closure11.doCall(/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle:265)
10:09:45.989 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:444)
10:09:45.989 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:432)
10:09:45.989 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.DefaultTaskExecuter.executeActions(DefaultTaskExecuter.java:58)
10:09:45.990 [ERROR] [org.gradle.BuildExceptionReporter]    ... 27 more
</code>

At last, tried rm -rf  /Users/jeppe/.gem/ && export GEM_HOME=/Users/jeppe/.gem/jruby

This seems to install the first gem and then exit the build script?? Running again fails with the next   project.useGem('activerecord')
<code>
10:14:00.483 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.IllegalArgumentException: Neither path nor baseDir may be null or empty string. path='null' basedir='/Users/jeppe/Documents/workspaces/fleetzone/fleetweb'
10:14:00.483 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.BaseDirConverter.doResolve(BaseDirConverter.java:64)
10:14:00.483 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:48)
10:14:00.484 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:44)
10:14:00.484 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.BaseDirConverter.resolveAsRelativePath(BaseDirConverter.java:39)
10:14:00.484 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.file.DefaultFileOperations.relativePath(DefaultFileOperations.java:99)
10:14:00.485 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractProject.relativePath(AbstractProject.java:731)
10:14:00.485 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.Project$relativePath.call(Unknown Source)
10:14:00.485 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.Project$relativePath.call(Unknown Source)
10:14:00.485 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.ProjectExtPlugin$_apply_closure1.doCall(ProjectExtPlugin.groovy:13)
10:14:00.486 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure6.doCall(RunJRubyPlugin.groovy:61)
10:14:00.486 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure9.doCall(RunJRubyPlugin.groovy:93)
10:14:00.486 [ERROR] [org.gradle.BuildExceptionReporter]    at build_58n6pgnaovl3erg7mhkqgfg4q2.runDBTask(/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle:254)
10:14:00.486 [ERROR] [org.gradle.BuildExceptionReporter]    at build_58n6pgnaovl3erg7mhkqgfg4q2$_run_closure11.doCall(/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle:265)
10:14:00.487 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:444)
10:14:00.487 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:432)
10:14:00.487 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.DefaultTaskExecuter.executeActions(DefaultTaskExecuter.java:58)
10:14:00.487 [ERROR] [org.gradle.BuildExceptionReporter]    ... 27 more 
</code>

Any hints?

/Jeppe

**Comment by RobertFischer** [comment]
RunJRuby plugin presumes you don't have a JRuby kicking around, so it installs a copy itself. A check for an existing JRuby (perhaps via JRUBY_HOME or scanning the path or something) would be possible, but I just haven't bothered to implement it yet.

It looks like you've got some kind of permissions issue going on, but there may be another issue.with the path/baseDir thing. I'll take a look at it later today.

**Comment by jeppenejsum** [comment]
That was my understanding as well. I don't have any jruby installed. 

If you look at the stack trace, it looks like it tries to install the gem inside the jruby jar file. Probably not the best place :-)

Let me know if there's some more info I can provide....or if you're too busy to look into it I'll have a look at some point.

**Comment by RobertFischer** [comment]
Yeah, and I'm not sure why it's doing that. The fact that it's an IllegalStateException and not a GradleException makes me a bit suspicious.

Can you run with -d?  I'm looking for where it placed your GEM_HOME, and I suspect we're going to see messages like "$dir does not exist: cannot find bin dir for $gem"

I can't duplicate your behavior exactly, but I'd like to get it so that the project works for you.

**Comment by jeppenejsum** [comment]
Not sure how much you want, here's the last part of running

rm -rf ~/.gem && ./gradlew -d dbUpdateSchema

with some IvyLogging removed
<code>
14:59:38.959 [INFO] [org.gradle.BuildLogger] Tasks to be executed: [task ':dbUpdateSchema']
14:59:38.961 [LIFECYCLE] [org.gradle.TaskExecutionLogger] :dbUpdateSchema
14:59:38.962 [DEBUG] [org.gradle.api.internal.tasks.SkipTaskExecuter] Starting to execute task ':dbUpdateSchema'
14:59:38.968 [DEBUG] [org.gradle.api.internal.project.taskfactory.ExecutionShortCircuitTaskExecuter] Determining if task ':dbUpdateSchema' is up-to-date
14:59:39.134 [INFO] [org.gradle.api.internal.changedetection.DefaultTaskArtifactStateRepository] Executing task ':dbUpdateSchema' due to:
Task ':dbUpdateSchema' has not declared any outputs.
14:59:39.153 [DEBUG] [org.gradle.api.internal.project.taskfactory.ExecutionShortCircuitTaskExecuter] task ':dbUpdateSchema' is not up-to-date
14:59:39.154 [DEBUG] [org.gradle.api.internal.tasks.DefaultTaskExecuter] Executing actions for task ':dbUpdateSchema'.
14:59:39.229 [QUIET] [system.out] use Gem
14:59:39.267 [DEBUG] [com.smokejumperit.gradle.RunJRubyPlugin] Looking for Gem Home based on root project 'fleetweb': defaulting gem home to /Users/jeppe/.gem
14:59:39.300 [DEBUG] [com.smokejumperit.gradle.RunJRubyPlugin] /Users/jeppe/.gem does not exist: cannot find gem rake
14:59:39.301 [INFO] [com.smokejumperit.gradle.RunJRubyPlugin] Installing JRuby gem: rake
14:59:39.343 [DEBUG] [com.smokejumperit.gradle.RunJRubyPlugin] JRuby Commands: [-S, gem, install, --no-rdoc, --no-ri, rake]

...

14:59:40.269 [INFO] [com.smokejumperit.gradle.RunJRubyPlugin] Running JRuby: -S gem install --no-rdoc --no-ri rake
Fetching: rake-0.8.7.gem (100%)t] Fetching: rake-0.8.7.gem
14:59:55.343 [ERROR] [system.err] ERROR:  While executing gem ... (Gem::FilePermissionError)
14:59:55.349 [ERROR] [system.err]     You don't have write permissions into the file:/Users/jeppe/.gradle/cache/org.jruby/jruby-complete/jars/jruby-complete-1.6.0.jar!/META-INF/jruby.home/lib/ruby/gems/1.8 directory.

</code>

**Comment by jeppenejsum** [comment]
Here's a build.gradle that shows the problem (for me at least) when called like this:

rm -rf ~/.gem && ./gradlew -d dbUpdateSchema

apply {
  plugin com.smokejumperit.gradle.ProjectExtPlugin
  plugin com.smokejumperit.gradle.RunJRubyPlugin
}

buildscript {
  repositories {
    mavenCentral()
    mavenRepo urls:'http://repo.smokejumperit.com'
  }
  dependencies {
    classpath 'com.smokejumperit:gradle-plugins:0.7.1-SNAPSHOT'
  }
}

task wrapper(type: Wrapper) {
  gradleVersion = '1.0-milestone-1'
}

def runDBTask(task) {
   println("use Gem")
   project.useGem('rake')
   println("Rake done")
   project.useGem('activerecord')
   println("activerecord done")
   project.useGem('activerecord-jdbcpostgresql-adapter')
   println("jdbc done")
   def rakeBin = project.gemScript('rake')
   println("bin "+rakeBin)
   project.runJRuby("-C db $rakeBin $task DATABASE=fleetzone")
}

task dbUpdateSchema() << {
   runDBTask('db:migrate')
}

**Comment by RobertFischer** [comment]
gradlew, huh? I don't test for using it with gradlew. I suspect we may have a culprit. Let me see what I can do.

**Comment by jeppenejsum** [comment]
Hopefully that shouldn't matter (if so I think it's a gradle issue). I see it still fails using plain gradle (but I only have 0.9.2 installed, so may be different with 1.0-M1).

NB: Sorry about the pasted code layout :-)

**Comment by RobertFischer** [comment]
It looks like it's a consequence of updating JRuby. Not sure why I didn't catch it locally. See if the newest SNAPSHOT works for you.

**Comment by jeppenejsum** [comment]
Thanks, a little progress: Now it installs a gem, but then seems to exit the gradle process after the call to useGem. By repeatedly running the gradle script (without the "rm -rf" part :-) I can get the gems installed. So far so good.

But now the script fails on the gemScript line:

16:14:41.737 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: groovy.lang.MissingMethodException: No signature of method: java.lang.String.exists() is applicable for argument types: () values: []
16:14:41.737 [ERROR] [org.gradle.BuildExceptionReporter] Possible solutions: wait(), next(), toList(), execute(), expand(), equals(java.lang.Object)
16:14:41.738 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure7.doCall(RunJRubyPlugin.groovy:68)
16:14:41.738 [ERROR] [org.gradle.BuildExceptionReporter]    at build_pvedn8o3fthnmua73ju19t560.runDBTask(/Users/jeppe/projects/test/gradle/build.gradle:28)
16:14:41.739 [ERROR] [org.gradle.BuildExceptionReporter]    at build_pvedn8o3fthnmua73ju19t560$_run_closure3.doCall(/Users/jeppe/projects/test/gradle/build.gradle:34)
16:14:41.739 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:444)
16:14:41.740 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:432)
16:14:41.740 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.DefaultTaskExecuter.executeActions(DefaultTaskExecuter.java:58)

Note that this code used to work in earlier versions of gradle & the plugins, but I can't pinpoint exactly when it started to fail. The end goal is to run the rake command to do a db migration.

**Comment by RobertFischer** [comment]
Thanks for working with me on this; I'm on a work computer, so I can't test it. Try the newest snapshot (*-6).

**Comment by jeppenejsum** [comment]
Well, thanks for looking into this in the first place. I think it's a step backwards. I now get this (with a clean .gem dir)

Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.io.File(java.io.File)
16:25:33.001 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure6.doCall(RunJRubyPlugin.groovy:45)
16:25:33.002 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure9.doCall(RunJRubyPlugin.groovy:96)
16:25:33.003 [ERROR] [org.gradle.BuildExceptionReporter]    at build_pvedn8o3fthnmua73ju19t560.runDBTask(/Users/jeppe/projects/test/gradle/build.gradle:22)
16:25:33.003 [ERROR] [org.gradle.BuildExceptionReporter]    at build_pvedn8o3fthnmua73ju19t560$_run_closure3.doCall(/Users/jeppe/projects/test/gradle/build.gradle:34)
16:25:33.005 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:444)
16:25:33.006 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:432)
16:25:33.007 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.DefaultTaskExecuter.executeActions(DefaultTaskExecuter.java:58)

**Comment by RobertFischer** [comment]
I overcorrected. Try *-7.  (This is the a pretty lousy way to do TDD, but it's the best I can do right now...)

**Comment by jeppenejsum** [comment]
:-) 

Much better. Now seems to actually start rake (get an error in the test script but that's to be expected).

Still exits gradle after each gem install though.

**Comment by RobertFischer** [comment]
Actually, it exits after each call to JRuby.  Try *-8.

**Comment by jeppenejsum** [comment]
Not good:

Caused by: java.lang.NullPointerException: Cannot invoke method loadClass() on null object
16:56:37.024 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure8.doCall(RunJRubyPlugin.groovy:94)
16:56:37.025 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure8.doCall(RunJRubyPlugin.groovy)
16:56:37.025 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure9.doCall(RunJRubyPlugin.groovy:110)
16:56:37.025 [ERROR] [org.gradle.BuildExceptionReporter]    at build_58n6pgnaovl3erg7mhkqgfg4q2.runDBTask(/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle:253)
16:56:37.025 [ERROR] [org.gradle.BuildExceptionReporter]    at build_58n6pgnaovl3erg7mhkqgfg4q2$_run_closure11.doCall(/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle:265)
16:56:37.026 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:444)
16:56:37.026 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:432)
16:56:37.026 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.DefaultTaskExecuter.executeActions(DefaultTaskExecuter.java:58)
16:56:37.026 [ERROR] [org.gradle.BuildExceptionReporter]    ... 27 more

**Comment by RobertFischer** [comment]
That one was my bad. *-9

**Comment by jeppenejsum** [comment]
Oops, seems my last comment wasn't posted and I've been offline...

*-9 fails with:

Caused by: groovy.lang.MissingPropertyException: No such property: new for class: org.jruby.RubyInstanceConfig
21:13:14.250 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure8.doCall(RunJRubyPlugin.groovy:95)
21:13:14.250 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure8.doCall(RunJRubyPlugin.groovy)
21:13:14.250 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure9.doCall(RunJRubyPlugin.groovy:110)
21:13:14.251 [ERROR] [org.gradle.BuildExceptionReporter]    at build_58n6pgnaovl3erg7mhkqgfg4q2.runDBTask(/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle:253)
21:13:14.251 [ERROR] [org.gradle.BuildExceptionReporter]    at build_58n6pgnaovl3erg7mhkqgfg4q2$_run_closure11.doCall(/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle:265)
21:13:14.251 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:444)
21:13:14.251 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:432)
21:13:14.252 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.DefaultTaskExecuter.executeActions(DefaultTaskExecuter.java:58)
21:13:14.252 [ERROR] [org.gradle.BuildExceptionReporter]    ... 27 more

**Comment by RobertFischer** [comment]
Okay, for real, I think I've got it this time: *-12.

Soon enough, I'll be at home and able to do the testing personally.

**Comment by jeppenejsum** [comment]
Not quite. Feeling quite embarrassed for not actually trying to solve this myself :-)....take your time, it's not a show stopper.

21:32:36.470 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: groovy.lang.MissingMethodException: No signature of method: static org.jruby.Main.new() is applicable for argument types: (org.jruby.RubyInstanceConfig) values: [org.jruby.RubyInstanceConfig@2a163765]
21:32:36.470 [ERROR] [org.gradle.BuildExceptionReporter] Possible solutions: run(), any(), run([Ljava.lang.String;), is(java.lang.Object), use([Ljava.lang.Object;), any(groovy.lang.Closure)
21:32:36.470 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure8.doCall(RunJRubyPlugin.groovy:101)
21:32:36.471 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure8.doCall(RunJRubyPlugin.groovy)
21:32:36.471 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin$_apply_closure9.doCall(RunJRubyPlugin.groovy:110)
21:32:36.471 [ERROR] [org.gradle.BuildExceptionReporter]    at build_58n6pgnaovl3erg7mhkqgfg4q2.runDBTask(/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle:253)
21:32:36.472 [ERROR] [org.gradle.BuildExceptionReporter]    at build_58n6pgnaovl3erg7mhkqgfg4q2$_run_closure11.doCall(/Users/jeppe/Documents/workspaces/fleetzone/fleetweb/build.gradle:265)
21:32:36.472 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:444)
21:32:36.481 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:432)
21:32:36.482 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.tasks.DefaultTaskExecuter.executeActions(DefaultTaskExecuter.java:58)
21:32:36.482 [ERROR] [org.gradle.BuildExceptionReporter]    ... 27 more

**Comment by RobertFischer** [comment]
So...close....

**Comment by RobertFischer** [comment]
And by that, I mean, "Try *-14".

**Comment by jeppenejsum** [comment]
Actually got *-15. Now it seems the plugin itself works, but I now get a jruby error

21:49:12.400 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- jruby/commands

No further stack trace. I tried deleting jruby\* from the gradle cache, no change. 

I know very little jruby. Did anything change in initialization that could cause this?

**Comment by RobertFischer** [comment]
Shit.  That means JRuby is barfing about being in a JAR.

I updated JRuby versions. That's where all this mess happened.  I remembered not updating for a good reason, but I couldn't remember what it was.

Is there an implementation of embedded JRuby anywhere else? Or am I the only person doing this?

**Comment by jeppenejsum** [comment]
Strange thing is, it actually worked. At least for a single command :-) But I suppose the fix for this caused jruby to fail...

**Comment by RobertFischer** [comment]
Yeah, it's a config issue. In order to get JRuby to stop calling System.exit, I had to pass in an instance of RubyInstanceConfig instead of just calling the static main method directly. But now it's unable to find the commands directory. Looking at the source code, I'm not at all sure why that would be true.

I've got a *-17 out there.  See how that treats you. I'm heading home for the night.

**Comment by jeppenejsum** [comment]
17 is no different :-(

**Comment by jeppenejsum** [comment]
17 is no different :-(
