### ISSUE TITLE
Guice + OneJar

### ISSUE THREAD

**Issue by RobertFischer** [RobertFischer/gradle-plugins#5]
See here: https://github.com/RobertFischer/gradle-plugins/issues#issue/4/comment/720118

It seems to be because I'm using Guice and because of the classpath funkiness that oneJar does. It looks like you have to include an extra oneJar library in order to use Guice:
http://one-jar.sourceforge.net/index.php?page=frameworks&file=guice

**Comment by RobertFischer** [comment]
Actually, it looks like the 0.98 release of OneJar might solve this problem in a better way.  Going to try updating, and then we'll see how it works.

**Comment by RobertFischer** [comment]
Try the 0.7.0 release. I bet that works a lot better for you.

**Comment by benmccann** [comment]
Thanks Robert!  I tested and it does seems to work much better.
I'm still having some trouble, but it seems to be issues with OneJar itself and not the Gradle plugin:
https://sourceforge.net/tracker/?func=detail&aid=3202537&group_id=111153&atid=658457
https://sourceforge.net/tracker/?func=detail&aid=3202478&group_id=111153&atid=658457

Thanks again,
Ben
