### ISSUE TITLE
Better error message when Main-Class undefined

### ISSUE THREAD

**Issue by benmccann** [RobertFischer/gradle-plugins#6]
I forgot to define a Main-Class (I had no jar task at all and relied on the default):
    jar {
      manifest {
        attributes 'Main-Class': 'com.benmccann.test.frontend.server.WebServer'
      }
    }

I got the error:
- What went wrong:
  Execution failed for task ':java/com/benmccann/test/frontend:oneJar'.
  Cause: Could not find property 'oneJar' on task ':java/com/benmccann/test/frontend:oneJar'.

It wasn't real obvious what I had done wrong.  It might be helpful to provide a better error message for this case.

**Comment by RobertFischer** [comment]
That's a good point, and it's easy enough to check.

Thanks for the feedback on the plugin.

BTW, I'm still working on integrating the newer version fo OneJar, which should work with Guice without hackery.

**Comment by benmccann** [comment]
Awesome!  Thanks :o)

**Comment by RobertFischer** [comment]
Fixed in master a961c9e571c13ccb4d51

https://github.com/RobertFischer/gradle-plugins/commit/a961c9e571c13ccb4d514d7a8f0eeb77e51e95fd
