### ISSUE TITLE
Could not find property 'taskGraph' on project

### ISSUE THREAD

**Issue by benmccann** [RobertFischer/gradle-plugins#7]
I tried updating to 0.7.0-SNAPSHOT and received an error running "gradle jar":
Cause: Could not find property 'taskGraph' on project

I think the line:
project.taskGraph.whenReady { graph ->

Should be changed to:
project.gradle.taskGraph.whenReady { graph ->

See http://gradle.org/0.9/docs/javadoc/org/gradle/api/Project.html

**Comment by RobertFischer** [comment]
Fixed in the 0.7.0 release.
