### ISSUE TITLE
No signature of method: org.gradle.api.java.archives.internal.DefaultAttributes.contains()

### ISSUE THREAD

**Issue by benmccann** [RobertFischer/gradle-plugins#8]
I tried updating to 0.7.0-SNAPSHOT and received an error running "gradle oneJar":
- What went wrong:
  Failed to notify task execution graph listener.
  Cause: groovy.lang.MissingMethodException: No signature of method: org.gradle.api.java.archives.internal.DefaultAttributes.contains() is applicable for argument types: (java.lang.String) values: [Main-Class]

I think the line:
if(!jarTask.manifest.attributes.contains('Main-Class')) {

Should be changed to:
if(!jarTask.manifest.attributes.containsKey('Main-Class')) {

See https://github.com/gradle/gradle/blob/c9a958060278506903b41cb08ae11798ef711214/subprojects/gradle-plugins/src/main/groovy/org/gradle/api/java/archives/internal/DefaultAttributes.java

**Comment by benmccann** [comment]
FYI, if you're able to update version 0.7.0-SNAPSHOT to include the fixes for issues 7 and 8 then I'll retest to see if it works.  Luckily they're both one line fixes :o)

**Comment by RobertFischer** [comment]
Fixed in the 0.7.0 release.
